import React, { useCallback, useEffect, useState } from 'react';
import { reportAPI } from '../../api';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { Loader2, RefreshCw, FileText } from 'lucide-react';
import { ReportDocumentView } from './ReportDocumentView';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../ui/select';
import { cn } from '../ui/utils';

type ReportRow = { id: string; type: string; generatedAt: string; insufficientData?: boolean };

/** Clinician read-only: therapist-generated clinician reports for this case. */
export function ClinicianCaseReports({ caseId }: { caseId: string }) {
  const [list, setList] = useState<ReportRow[]>([]);
  const [loadingList, setLoadingList] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [detail, setDetail] = useState<{ type: string; data: Record<string, unknown> } | null>(null);
  const [loadingDetail, setLoadingDetail] = useState(false);

  const loadList = useCallback(async () => {
    if (!caseId) return;
    setLoadingList(true);
    setError(null);
    try {
      const res = await reportAPI.listByCase(caseId);
      setList((res.data?.data || []) as ReportRow[]);
    } catch (e: unknown) {
      const err = e as { response?: { data?: { message?: string } } };
      setError(err.response?.data?.message || 'Failed to load reports');
      setList([]);
    } finally {
      setLoadingList(false);
    }
  }, [caseId]);

  useEffect(() => {
    void loadList();
  }, [loadList]);

  const loadDetail = async (id: string) => {
    setSelectedId(id);
    setLoadingDetail(true);
    setError(null);
    try {
      const res = await reportAPI.getById(id);
      const d = res.data?.data;
      setDetail({
        type: d?.type || '',
        data: (d?.data || {}) as Record<string, unknown>,
      });
    } catch (e: unknown) {
      const err = e as { response?: { data?: { message?: string } } };
      setError(err.response?.data?.message || 'Failed to load report');
      setDetail(null);
    } finally {
      setLoadingDetail(false);
    }
  };

  const clinicianOnly = list.filter((r) => r.type === 'clinician');

  return (
    <Card className="border-slate-200 bg-white shadow-sm">
      <CardHeader className="border-b border-slate-100 bg-sky-50/50">
        <CardTitle className="flex items-center gap-2 text-base text-sky-900">
          <FileText className="h-5 w-5 text-sky-600" />
          Therapy reports (clinician view)
        </CardTitle>
        <CardDescription>
          Read-only summaries generated by the treating therapist. Generation happens from the therapist case file.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4 pt-6">
        {error ? (
          <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-800">{error}</div>
        ) : null}
        <div className="flex items-center gap-2">
          <Button type="button" variant="ghost" size="sm" onClick={() => void loadList()} disabled={loadingList}>
            <RefreshCw className={cn('mr-2 h-4 w-4', loadingList && 'animate-spin')} />
            Refresh
          </Button>
        </div>
        <div className="grid gap-4 lg:grid-cols-2 lg:items-start">
          <div>
            {loadingList ? (
              <p className="flex items-center gap-2 text-sm text-slate-500">
                <Loader2 className="h-4 w-4 animate-spin" /> Loading…
              </p>
            ) : clinicianOnly.length === 0 ? (
              <p className="text-sm text-slate-500">No clinician reports yet. Ask the therapist to generate one.</p>
            ) : (
              <Select
                value={selectedId || undefined}
                onValueChange={(v) => {
                  void loadDetail(v);
                }}
              >
                <SelectTrigger className="bg-white">
                  <SelectValue placeholder="Select a clinician report" />
                </SelectTrigger>
                <SelectContent>
                  {clinicianOnly.map((r) => (
                    <SelectItem key={r.id} value={r.id}>
                      {new Date(r.generatedAt).toLocaleString()}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            )}
          </div>
          <div className="min-h-[160px] rounded-lg border border-slate-200 bg-white p-3">
            {loadingDetail ? (
              <div className="flex justify-center py-12">
                <Loader2 className="h-8 w-8 animate-spin text-sky-600" />
              </div>
            ) : detail ? (
              <ReportDocumentView reportType={detail.type} payload={detail.data} />
            ) : (
              <p className="py-8 text-center text-sm text-slate-500">Select a report.</p>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
